export type Service = {
  slug: string;
  title: string;
  short: string;
  long: string;
  benefits: string[];
  category: 'Bewertung' | 'Schaden' | 'Bau' | 'Energie';
  icon: string;
};

export const SERVICES: Service[] = [
  { slug: 'immobilienbewertung', title: 'Immobilienbewertung', short: 'Marktwert ermitteln — fundiert, schnell und transparent.', long: 'Eine professionelle Immobilienbewertung schafft die Grundlage für jede wichtige Entscheidung — ob Verkauf, Kauf, Erbschaft oder Finanzierung. Wir analysieren Lage, Zustand, Marktdynamik und vergleichbare Objekte und liefern Ihnen eine belastbare Einschätzung.', benefits: ['Vergleichswert-, Ertrags- und Sachwertverfahren', 'Berücksichtigung lokaler Marktdaten', 'Verständliche Aufbereitung', 'In 7–14 Tagen'], category: 'Bewertung', icon: 'Building2' },
  { slug: 'immobiliengutachten', title: 'Immobiliengutachten', short: 'Detailliertes Gutachten für jede Lebenslage.', long: 'Unser Immobiliengutachten geht in die Tiefe: Bauzustand, Ausstattung, Modernisierungsstand und alle wertbeeinflussenden Faktoren werden umfassend dokumentiert und bewertet.', benefits: ['Vor-Ort-Begehung mit Fotodokumentation', 'Plausibilisierung aller Werte', 'Anerkennung durch Banken & Behörden', 'Auf Wunsch Kurz- oder Vollgutachten'], category: 'Bewertung', icon: 'FileSearch' },
  { slug: 'verkehrswertgutachten', title: 'Verkehrswertgutachten', short: 'Nach §194 BauGB — gerichts- und finanzamtsfest.', long: 'Das Verkehrswertgutachten nach §194 BauGB ist die Königsdisziplin der Immobilienbewertung. Anerkannt von Gerichten, Finanzämtern und Behörden — die richtige Wahl bei Erbe, Scheidung, Steuer und juristischen Auseinandersetzungen.', benefits: ['Vollständig nach ImmoWertV', 'Anerkannt durch Finanzamt & Gericht', 'DEKRA-zertifizierte Methodik', 'Inkl. ausführlicher Begründung'], category: 'Bewertung', icon: 'Scale' },
  { slug: 'kaufberatung-beim-erwerb-von-immobilien', title: 'Kaufberatung', short: 'Vor dem Notar wissen, was Sie kaufen.', long: 'Der Immobilienkauf ist meist die größte Investition Ihres Lebens. Wir begleiten Sie vor Ort, prüfen Bausubstanz, Unterlagen und Marktpreis — und schützen Sie vor teuren Fehlentscheidungen.', benefits: ['Gemeinsame Besichtigung', 'Bauliche Risiken identifizieren', 'Preis-Verhandlungsbasis', 'Klare Handlungsempfehlung'], category: 'Bewertung', icon: 'ShieldCheck' },
  { slug: 'restnutzungsdauer', title: 'Restnutzungsdauer', short: 'Steuerlast senken durch fundiertes Gutachten.', long: 'Mit einem Restnutzungsdauer-Gutachten können Sie die AfA Ihrer vermieteten Immobilie deutlich erhöhen und mehrere tausend Euro Steuern pro Jahr sparen — anerkannt durch das Finanzamt.', benefits: ['Höhere AfA = weniger Steuern', 'Anerkennung durch das Finanzamt', 'BFH-konforme Methodik', 'Schnelle Bearbeitung'], category: 'Bewertung', icon: 'TrendingDown' },
  { slug: 'versicherungsschaden-gutachter', title: 'Versicherungsschäden', short: 'Ihre Ansprüche gegen die Versicherung durchsetzen.', long: 'Ob Wasser-, Feuer- oder Sturmschaden — als unabhängiger Gutachter dokumentieren und bewerten wir den Schaden objektiv und unterstützen Sie bei der Auseinandersetzung mit Ihrer Versicherung.', benefits: ['Unabhängige Schadensbewertung', 'Vollständige Dokumentation', 'Verhandlung mit Versicherern', 'Beweissichernde Arbeit'], category: 'Schaden', icon: 'Droplets' },
  { slug: 'gutachter-schimmelpilz', title: 'Schimmelpilz-Gutachten', short: 'Ursache finden, Haftung klären, Sanierung planen.', long: 'Schimmel ist ein Gesundheitsrisiko und juristisches Streitthema. Wir identifizieren die Ursache, klären die Haftung zwischen Mieter und Vermieter und empfehlen die richtige Sanierung.', benefits: ['Ursachenanalyse mit Messtechnik', 'Mieter- vs. Vermieter-Haftung', 'Sanierungskonzept', 'Gutachten für Gericht'], category: 'Schaden', icon: 'AlertTriangle' },
  { slug: 'baubegleitung', title: 'Baubegleitung', short: 'Ihr unabhängiger Qualitätswächter auf der Baustelle.', long: 'Während der Bauphase prüfen wir regelmäßig Ausführungsqualität, Bauzeitenplan und Materialeinsatz. So vermeiden Sie teure Mängel, bevor sie unsichtbar in der Wand verschwinden.', benefits: ['Regelmäßige Vor-Ort-Termine', 'Mängel sofort dokumentieren', 'Abnahme-Begleitung', 'Schutz Ihrer Investition'], category: 'Bau', icon: 'HardHat' },
  { slug: 'gutachter-fur-bauschaden', title: 'Bauschäden-Gutachter', short: 'Ursachen aufdecken, Verantwortliche benennen.', long: 'Risse, Feuchtigkeit, Setzungen — bei Bauschäden zählt eine fundierte Analyse. Wir benennen die Ursache, dokumentieren beweissicher und unterstützen bei der Durchsetzung Ihrer Ansprüche.', benefits: ['Ursachenanalyse', 'Beweissicherung', 'Sanierungsempfehlung', 'Gerichtsverwertbar'], category: 'Bau', icon: 'Hammer' },
  { slug: 'energieausweis', title: 'Energieausweis', short: 'Pflicht beim Verkauf — wir stellen ihn schnell aus.', long: 'Beim Verkauf oder der Vermietung Ihrer Immobilie ist der Energieausweis Pflicht. Wir erstellen Verbrauchs- oder Bedarfsausweis schnell, korrekt und gesetzeskonform.', benefits: ['Verbrauchs- oder Bedarfsausweis', 'GEG-konform', 'Innerhalb weniger Tage', 'Festpreis'], category: 'Energie', icon: 'Zap' },
  { slug: 'energieberatung', title: 'Energieberatung', short: 'Förderungen sichern, Kosten senken.', long: 'Mit einer geförderten Energieberatung (BAFA / KfW) entwickeln wir mit Ihnen einen individuellen Sanierungsfahrplan, der Ihre Heizkosten senkt und den Wert Ihrer Immobilie steigert.', benefits: ['BAFA-/KfW-Förderfähig', 'Individueller Sanierungsfahrplan', 'Höhere Förderquoten möglich', 'Wertsteigerung der Immobilie'], category: 'Energie', icon: 'Leaf' },
];
